"""migrate

Revision ID: 2d723727ca33
Revises: 
Create Date: 2020-05-29 16:47:43.200967

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d723727ca33'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'author_song', type_='foreignkey')
    op.drop_constraint(None, 'author_song', type_='foreignkey')
    op.create_foreign_key(None, 'author_song', 'author', ['author_id'], ['id'])
    op.create_foreign_key(None, 'author_song', 'song', ['song_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'author_song', type_='foreignkey')
    op.drop_constraint(None, 'author_song', type_='foreignkey')
    op.create_foreign_key(None, 'author_song', 'author', ['author_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'author_song', 'song', ['song_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
