"""fix trial

Revision ID: bcfe9af3872f
Revises: 
Create Date: 2020-06-17 02:35:35.291335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bcfe9af3872f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'account', ['role'])
    op.create_unique_constraint(None, 'poem', ['account_role'])
    op.create_unique_constraint(None, 'song', ['account_role'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'song', type_='unique')
    op.drop_constraint(None, 'poem', type_='unique')
    op.drop_constraint(None, 'account', type_='unique')
    # ### end Alembic commands ###
